name: Build and Deploy Resume

on:
  push:
    branches:
      - main  # Trigger only when you push to the main branch

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This allows the action to upload the PDF to your Releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Compile LaTeX Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      
      - name: Release Updated Resume
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
          tag_name: latest
          name: "Latest Resume Build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}